# Generated by Django 6.0.7 on 2026-07-22 02:20

import detection.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=detection.models.submission_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='e.g. ViT-DeepfakeDetector-v1', max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('manipulation_score', models.FloatField(help_text='0.0 (authentic) to 1.0 (manipulated).')),
                ('verdict', models.CharField(choices=[('authentic', 'Likely Authentic'), ('manipulated', 'Likely Manipulated'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('anomaly_regions', models.JSONField(default=list, help_text='List of {box, label, confidence} from YOLOv8/Detectron2 region flags.')),
                ('heatmap_image', models.ImageField(blank=True, help_text='Grad-CAM overlay.', null=True, upload_to=detection.models.heatmap_upload_path)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_analysis', to='detection.imagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FactCheckReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('claim_review_url', models.URLField(max_length=500)),
                ('publisher_name', models.CharField(blank=True, max_length=255)),
                ('rating_text', models.CharField(blank=True, max_length=100)),
                ('rating_date', models.DateField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_checks', to='detection.imagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_index', models.PositiveSmallIntegerField()),
                ('bounding_box', models.JSONField(help_text='[top, right, bottom, left] in pixels.')),
                ('detection_confidence', models.FloatField()),
                ('embedding', models.JSONField(blank=True, help_text='128/512-d face embedding vector for matching.', null=True)),
                ('deepface_emotion', models.CharField(blank=True, max_length=50)),
                ('deepface_age_estimate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='detection.imagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ExifMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_exif', models.JSONField(default=dict, help_text='Full raw ExifTool output.')),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('software_tag', models.CharField(blank=True, help_text="Editing software tag, e.g. 'Adobe Photoshop 25.0'", max_length=150)),
                ('capture_timestamp', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('has_discrepancy', models.BooleanField(default=False, help_text='True if EXIF is missing/stripped/inconsistent with claimed provenance.')),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exif', to='detection.imagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_verdict', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('summary_text', models.TextField()),
                ('review_status', models.CharField(choices=[('auto_generated', 'Auto-generated (unreviewed)'), ('human_reviewed', 'Human-reviewed'), ('disputed', 'Disputed')], default='auto_generated', max_length=20)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='detection.imagesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseImageMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('source_domain', models.CharField(blank=True, max_length=255)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('first_indexed_date', models.DateField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_matches', to='detection.imagesubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='imagesubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='detection_i_status_c03602_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facedetection',
            unique_together={('submission', 'face_index')},
        ),
    ]
