# Generated by Django 6.0.7 on 2026-07-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_code', models.CharField(help_text="Machine-readable code, e.g. 'identity_fraud'. Used as the LegalMapping lookup key.", max_length=50)),
                ('tag_label', models.CharField(help_text='Human-readable label shown in the UI.', max_length=150)),
                ('rule_description', models.TextField(help_text='Explains which detections triggered this tag, for auditability.')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='detection.imagesubmission')),
            ],
        ),
    ]
