# Generated by Django 6.0.7 on 2026-07-23 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_taggingresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reverseimagematch',
            options={'ordering': ['-similarity_score']},
        ),
        migrations.RenameField(
            model_name='factcheckreference',
            old_name='rating_date',
            new_name='review_date',
        ),
        migrations.RemoveField(
            model_name='factcheckreference',
            name='claim_review_url',
        ),
        migrations.RemoveField(
            model_name='factcheckreference',
            name='rating_text',
        ),
        migrations.RemoveField(
            model_name='reverseimagematch',
            name='first_indexed_date',
        ),
        migrations.RemoveField(
            model_name='reverseimagematch',
            name='match_confidence',
        ),
        migrations.RemoveField(
            model_name='reverseimagematch',
            name='source_domain',
        ),
        migrations.RemoveField(
            model_name='reverseimagematch',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='reverseimagematch',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='factcheckreference',
            name='claimant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='factcheckreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcheckreference',
            name='publisher_url',
            field=models.URLField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcheckreference',
            name='rating',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='domain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='match_type',
            field=models.CharField(choices=[('EXACT', 'Exact Match'), ('PARTIAL', 'Partial Match'), ('SIMILAR', 'Visually Similar')], default='SIMILAR', max_length=50),
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='page_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='page_url',
            field=models.URLField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reverseimagematch',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factcheckreference',
            name='publisher_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factcheckreference',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_check_references', to='detection.imagesubmission'),
        ),
        migrations.AlterField(
            model_name='taggingresult',
            name='tag_code',
            field=models.CharField(help_text="Machine-readable code, e.g. 'identity_fraud'.", max_length=50),
        ),
    ]
