# Generated by Django 6.0.7 on 2026-07-22 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('upload', 'Image Uploaded'), ('exif_check', 'EXIF Metadata Checked'), ('face_detect', 'Face Detection Run'), ('forensic_analysis', 'Forensic Analysis Run'), ('reverse_search', 'Reverse Image Search Run'), ('fact_check', 'Fact-Check Lookup Run'), ('report_generated', 'Report Generated'), ('report_reviewed', 'Report Reviewed by Human'), ('export', 'Report Exported')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the action was performed by an automated pipeline step.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='detection.imagesubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['submission', 'timestamp'], name='audit_audit_submiss_4a26ab_idx')],
            },
        ),
    ]
