# Generated by Django 6.0.7 on 2026-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('upload', 'Image Uploaded'), ('exif_check', 'EXIF Metadata Checked'), ('face_detect', 'Face Detection Run'), ('forensic_analysis', 'Forensic Analysis Run'), ('tagging', 'Tagging Layer Run'), ('reverse_search', 'Reverse Image Search Run'), ('fact_check', 'Fact-Check Lookup Run'), ('report_generated', 'Report Generated'), ('report_reviewed', 'Report Reviewed by Human'), ('export', 'Report Exported')], max_length=30),
        ),
    ]
