# Generated by Django 6.0.7 on 2026-07-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(help_text="e.g. 'Cybercrime Prevention Act of 2012'", max_length=255)),
                ('law_number', models.CharField(help_text="e.g. 'RA 10175'", max_length=50)),
                ('section', models.CharField(blank=True, help_text="e.g. 'Sec. 4(b)(3)'", max_length=50)),
                ('description', models.TextField()),
                ('jurisdiction', models.CharField(default='Philippines', max_length=100)),
            ],
            options={
                'ordering': ['law_number', 'section'],
                'unique_together': {('law_number', 'section')},
            },
        ),
        migrations.CreateModel(
            name='LegalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_condition', models.CharField(help_text="e.g. 'manipulated_verdict_high_confidence', 'face_swap_of_public_official'", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_mappings', to='detection.detectionreport')),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='legalmap.legalprovision')),
            ],
            options={
                'unique_together': {('report', 'provision', 'trigger_condition')},
            },
        ),
    ]
