# Generated by Django 6.0.7 on 2026-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalprovision',
            name='status',
            field=models.CharField(choices=[('enacted', 'Enacted Law'), ('pending_bill', 'Pending Bill (not yet law)')], default='enacted', help_text='Whether this is currently enacted law or a pending bill — do not present pending bills as current law.', max_length=20),
        ),
    ]
